### PR TITLE
Stable version of Snoopy is installed using his install script

### PR DESCRIPTION
**Pull request by myjapan**
Hello
I've edited your role to install snoopy using the script install-snoopy.sh

### CODE REVIEW

**Comment by tkimball83** [comment]
Hey @myjapan, thanks for the PR!

Unfortunately there are a few issues with this pull request.  I'm happy to modify this role to remove the rpm dependency and use the snoopy provided install script however.  I'll list the issues below.

- It looks like you're using ansible >= 2.10 due to the naming of the modules you're including.  However, the rest of the tasks are using the older <= 2.9 syntax.  We should keep this consistent, and I recommend using the <= 2.9 naming schema for now since 2.10 seems to have naming backwards compatibility. 
- Instead of writing directly to /tmp, the tempfile module should be used to create randomized temporary directories to prevent race conditions.
- As for the script download task, I'm not sure why you would only want to `run_once` unless you have a shared /tmp directory across nodes.  This should be removed so a group of nodes can all download and execute the install script independently. 

With all that said, I'm happy to make the modifications you're requesting as well.  Just let me know and I can put together a branch for you to test.

Thanks!

**Comment by myjapan** [comment]
Hi, thanks @tkimball83 
There is a new commit:

- Yes, I'm using Ansible v. 2.10 -- I've changed the naming of the modules using the <= 2.9 schema
- Now the role uses the tempfile module, and the install-script.sh is downloaded and executed directly on the remote host

All the best!

**Comment by tkimball83** [comment]
Thanks @myjapan - I do have one more request.  Please add the default `tags` to all the of tasks, and `become` where necessary, and then we can get this merged.

**Comment by myjapan** [comment]
Hey @tkimball83,
I've added the soppy tags and become option to the tasks

**Review by tkimball83 — APPROVED** [review]

**Pull request merged**
